# Generated by Django 4.0.4 on 2022-05-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klijent',
            name='mojTrener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betterLife.trener'),
        ),
    ]
