# Generated by Django 4.0.4 on 2022-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='pfp',
        ),
        migrations.AddField(
            model_name='jelo',
            name='slika',
            field=models.ImageField(null=True, upload_to='imgs/jela'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='slika',
            field=models.ImageField(null=True, upload_to='imgs/korisnici'),
        ),
        migrations.AddField(
            model_name='sprava',
            name='slika',
            field=models.ImageField(null=True, upload_to='imgs/inventar'),
        ),
        migrations.AddField(
            model_name='vezba',
            name='slika',
            field=models.ImageField(null=True, upload_to='imgs/vezbe'),
        ),
    ]
