# Generated by Django 4.0.4 on 2022-05-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0002_alter_klijent_mojtrener'),
        ('betterLife', '0002_remove_korisnik_pfp_jelo_slika_korisnik_slika_and_more'),
    ]

    operations = [
    ]
