# Generated by Django 4.0.4 on 2022-05-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0003_merge_20220522_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'permissions': [('trener', 'treneru omogucava njegove funkcionalnosti')]},
        ),
    ]
