# Generated by Django 4.0.4 on 2022-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0005_alter_korisnik_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavka_treninga',
            name='brojPonavljanja',
            field=models.CharField(max_length=50),
        ),
    ]
