# Generated by Django 4.0.4 on 2022-05-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0007_stavka_treninga_rednibroj_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='razgovor',
            table='Razgovor',
        ),
    ]
