# Generated by Django 4.0.4 on 2022-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0012_rename_posaljilac_razgovor_posiljalac'),
    ]

    operations = [
        migrations.AddField(
            model_name='stavka_ishrane',
            name='redniBroj',
            field=models.IntegerField(default=0),
        ),
    ]
