# Generated by Django 4.0.4 on 2022-05-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0013_stavka_ishrane_rednibroj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavka_ishrane',
            name='redniBroj',
        ),
    ]
