# Generated by Django 4.0.4 on 2022-06-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0014_remove_stavka_ishrane_rednibroj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vezba',
            name='sprava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betterLife.sprava'),
        ),
    ]
