# Generated by Django 4.0.4 on 2022-06-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterLife', '0015_alter_vezba_sprava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klijent',
            name='brojClanskeKarte',
        ),
    ]
